### PR TITLE
proper fix for ATM

### PR DESCRIPTION
**Pull request by w1lla**

### CODE REVIEW

**Comment by oliverde8** [comment]
Hi, sorry but I don't like to much the message not using the translation system. The meta data is also missing which means the plugin won't show in the plugin list. And also it make more work for us as we need to test it (sorry but I don't even trust myself XD) And today we have already to much code in the package which slows down release process and stuff.  

I think we should remove it from the package(any way no one uses it as it doesen't have a metadata), and maybe you wish to release it yourself without putting it in the eXpansion package?

**Comment by w1lla** [comment]
It can be removed but it works properly within expansion so no harm is done actually

**Comment by oliverde8** [comment]
Well I don't mind but we should do it properly then, putting metadata and everything :)

**Comment by w1lla** [comment]
I did make a metadata... but it didnt come through i guess...

**Comment by w1lla** [comment]
https://github.com/eXpansionPluginPack/eXpansion/pull/130

**Comment by oliverde8** [comment]
this I didn't accepty because the window isn't using the proper components :smile: sorry but we try to normilize stufff to make it easier to maintain

**Pull request closed without merging**
