### PR TITLE
fix for grammar english

### PR DESCRIPTION
**Pull request by w1lla**

### CODE REVIEW

**Comment by MiniGod** [comment]
Looks like much more than just grammar fixes?

**Comment by w1lla** [comment]
weird i thought i did only a grammar fix ^^

2015-01-27 13:55 GMT+01:00 Kristjan Broder Lund <notifications@github.com>:

**Comment by oliverde8** [comment]
yes the changes on the logic troubled me quite a bit, next rime can you make you merge request on dev, because they might be fixed(the other merge request should for example). I need to test this first :smiley:

**Comment by w1lla** [comment]
bit not my cup of tea different branches ^^.

**Comment by reaby** [comment]
closing this as can't merge.

**Pull request closed without merging**
